export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAILURE = "FETCH_WEATHER_FAILURE";
export const CLEAR_WEATHER_DATA = "CLEAR_WEATHER_DATA";
export const CLEAR_WEATHER_ERROR = "CLEAR_WEATHER_ERROR";
